sudo: false
language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
before_install: gem install bundler -v 1.17.3
addons:
  code_climate:
    repo_token: be4f42e2cf6fb22ecf1028df50d055d41dc446b31b6b4f96c71fbe7d7ddff48c
